fix: CI pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,31 +1,55 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
 jobs:
   say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
     docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
       - image: cimg/base:current
 
-    # Add steps to the job
-    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
     steps:
-      # Checkout the code as the first step.
       - checkout
       - run:
           name: "Say hello"
           command: "echo Hello, World!"
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
+  lint:
+    docker:
+      - image: cimg/python:3.12.6
+    steps:
+      - checkout
+      - run:
+          name: Install deps
+          command: |
+            python -m pip install --upgrade pip
+            pip install flake8
+      - run:
+          name: Lint the code
+          command: |
+            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+      - run:
+          name: Checking if lint passed
+          command: |
+            if flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics | grep -q "0"; then
+              echo "Lint has passed and ready to merge"
+            else
+              echo "Lint failed, fix the issues"
+              exit 1
+            fi
+
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  pr-workflow:
     jobs:
-      - say-hello
+      - say-hello:
+          filters:
+            branches:
+              ignore: master
+            tags:
+              ignore: /.*/
+      - lint:
+          requires:
+            - say-hello
+          filters:
+            branches:
+              ignore: master
+            tags:
+              ignore: /.*/
